apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: bomdatafetcher
spec:
  createingress: true
  functionref:
    functionweights: null
    name: bomdatafetcher
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /fetch-bom-data
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /fetch-bom-data
